# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Abel Solutions
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://abelsolutions.co.nz" # the base hostname & protocol for your site

navigation:
  header:
    - name: Home
      url: /
    - name: Services
      url: /services/
    - name: Solutions
      url: /solutions/
    - name: Erp Functionality
      url: /erp-functionality/
    - name: Support
      url: /support/
    - name: About Us
      url: /about-us/
    - name: Contact
      url: /contact/
  footer:
    - name: Services
      url: /services/
    - name: Solutions
      url: /solutions/
    - name: Erp Functionality
      url: /erp-functionality/
    - name: Support
      url: /support/
    - name: About Us
      url: /about-us/


collections:
  staff:
    output: true
  testimonials:
    output: true
  case_studies:
    output: true

# Build settings
markdown: kramdown
sass:
    sass_dir: _sass

gems:
 - jekyll-coffeescript
